# Generated by Django 4.1.7 on 2023-03-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="accountstatus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="leadstatus",
            field=models.CharField(
                choices=[
                    ("1", "Active"),
                    ("2", "Hold"),
                    ("3", "Reject"),
                    ("4", "Pending"),
                ],
                default="N/A",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="phone_no",
            field=models.IntegerField(default=True, unique=True),
            preserve_default=False,
        ),
    ]
