# Generated by Django 4.1.7 on 2023-03-03 06:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_lead_accountstatus_lead_leadstatus_lead_phone_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="phone_no",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
