# Generated by Django 4.1.7 on 2023-03-03 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_lead_phone_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_BD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Gender",
                    models.CharField(
                        choices=[("1", "Mr."), ("2", "Mrs.")],
                        default="N/A",
                        max_length=20,
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="lead",
            name="leadsource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Lead",
                to="app.user_bd",
            ),
        ),
    ]
