# Generated by Django 4.1.7 on 2023-03-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_user_bd_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_bd",
            name="Gender",
            field=models.CharField(
                blank=True,
                choices=[("1", "Mr."), ("2", "Mrs.")],
                default="N/A",
                max_length=20,
                null=True,
            ),
        ),
    ]
