# Generated by Django 4.1.7 on 2023-03-03 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_user_bd_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenderAll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(default=False, max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name="user_bd",
            name="Gender",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.genderall",
            ),
            preserve_default=False,
        ),
    ]
