# Generated by Django 4.1.7 on 2023-03-03 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_genderall_alter_user_bd_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lead_id", models.CharField(max_length=255)),
                ("contact_first_name", models.CharField(max_length=255)),
                ("contact_last_name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("skype_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="lead",
            name="contact",
        ),
        migrations.AlterField(
            model_name="genderall",
            name="type",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="Contact",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.contact",
            ),
            preserve_default=False,
        ),
    ]
